export const TOGGLE_FORM = "TOGGLE_FORM";
export const TOGGLE_CONTACT_INFO = "TOGGLE_CONTACT_INFO";
export const ADD_CONTACT = "ADD_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const ADD_EDIT_CONTACT = "ADD_EDIT_CONTACT";


